version: "2"

services:
  client:
    build: 
      context: ./yeelight-controller-client/
      # dockerfile: Dockerfile.template
      dockerfile: Dockerfile.raspberry-pi
    restart: always
    network_mode: "host"
    
  api:
    build: 
      context: ./yeelight-controller-api/
      dockerfile: Dockerfile.template
    restart: always
    network_mode: "host"
