FROM arm32v6/node:14.9.0-alpine3.10 as build
WORKDIR /app
COPY package*.json ./
RUN npm install --production
COPY . .
RUN npm run build

FROM arm32v6/nginx:1.19.2-alpine
COPY --from=build /app/build /bin/www
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
CMD [ "nginx", "-g", "daemon off;" ]